spring.application.name=backend-gigshield
server.port=8085

weather.api.key=4aef3fbf29616c2643a2dd4d4730641e

spring.datasource.url=jdbc:mysql://localhost:3306/gigshield
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true